[project]
name = "my-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.1.0",
    "jinja2==3.1.6",
]
