name: Generate Static HTML

on:
  push:
    branches:
      - master  # Runs when changes are pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up UV
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          uv venv .venv
          source .venv/bin/activate

      - name: Install dependencies using UV
        run: |
          cd my_portfolio
          uv sync

      - name: Run Flask app and generate static files
        run: |
          cd my_portfolio
          export FLASK_APP=app.py
          flask run &  # Start Flask server in the background
          sleep 5  # Wait for Flask to fully start
          curl http://127.0.0.1:5000 -o ../index.html  # Save the main page as index.html

      - name: Move static files to root
        run: |
          mkdir -p ../static
          cp -r my_portfolio/static/* ../static/  # Copy all static files to root

      - name: Commit and push static files and index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html static/
          git commit -m "Update static site files [Automated]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/bonnybabukachappilly/bonnybabukachappilly.github.io.git master || echo "No changes to push"
