name: Generate Static HTML

on:
  push:
    branches:
      - master  # Runs when changes are pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2  # Updated to the latest version

      - name: Set up UV
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          uv venv my_portfolio/.venv
          source my_portfolio/.venv/bin/activate

      - name: Install dependencies using UV
        run: |
          cd my_portfolio
          uv sync

      - name: Run Flask app and generate static index.html
        run: |
          cd my_portfolio
          source .venv/bin/activate
          export FLASK_APP=app.py
          export FLASK_ENV=production
          flask run --host=127.0.0.1 --port=5000 &  # Start Flask in the background
          sleep 5  # Allow Flask to start
          curl http://127.0.0.1:5000 -o ../index.html  # Save rendered HTML

      - name: Move static files to root
        run: |
          mkdir -p ../static
          cp -r my_portfolio/static/* ../static/  # Copy all static files to root

      - name: Commit and push generated index.html
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Use the stored secret
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/bonnybabukachappilly/bonnybabukachappilly.github.io.git
          git add index.html
          git commit -m "Update static index.html [Automated]" || echo "No changes to commit"
          git push origin master || echo "No changes to push"
