name: Generate Static HTML

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up UV
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          uv venv my_portfolio/.venv
          source my_portfolio/.venv/bin/activate

      - name: Install dependencies using UV
        run: |
          cd my_portfolio
          uv sync

      - name: Run Flask app and generate static index.html
        run: |
          cd my_portfolio
          source .venv/bin/activate
          export FLASK_APP=app.py
          export FLASK_ENV=production
          flask run --host=127.0.0.1 --port=5000 &
          sleep 5
          curl http://127.0.0.1:5000 -o ../index.html
          cp -r static ../static

      - name: Commit and push static files and index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          if [ -d "static" ]; then git add static/; fi
          git commit -m "Update static site files [Automated]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/bonnybabukachappilly/bonnybabukachappilly.github.io.git master || echo "No changes to push"
