name: Generate Static HTML and Resume PDF

on:
  push:
    branches:
      - master  # Runs on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up UV
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          uv venv my_portfolio/.venv
          source my_portfolio/.venv/bin/activate

      - name: Install dependencies using UV
        run: |
          cd my_portfolio
          uv sync

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Run Flask app and generate static index.html
        run: |
          cd my_portfolio
          source .venv/bin/activate
          export FLASK_APP=app.py
          export FLASK_ENV=production
          flask run --host=127.0.0.1 --port=5000 &  # Start Flask in the background
          sleep 5  # Allow Flask to start
          curl http://127.0.0.1:5000 -o ../index.html  # Save rendered HTML

      - name: Copy static assets
        run: |
          cd my_portfolio
          cp -r static ../static

      - name: Generate Resume PDF with wkhtmltopdf
        run: |
          cd my_portfolio
          curl http://127.0.0.1:5000/resume -o resume.html  # Fetch the resume page
          wkhtmltopdf --page-size A4 resume.html ../resume.pdf  # Convert HTML to PDF

      - name: Commit and push generated files
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # GitHub Personal Access Token stored in secrets
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/bonnybabukachappilly/bonnybabukachappilly.github.io.git
          git add index.html static resume.pdf
          git commit -m "Update static HTML and resume PDF [Automated]" || echo "No changes to commit"
          git push origin master || echo "No changes to push"
